# Use the official Node.js image as base
FROM node:lts-iron

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the project dependencies
RUN npm install

# Copy the entire project to the working directory
COPY . .

# Rename example.env to .env
RUN mv example.env .env

# Expose the port on which the NestJS application will run
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "start:prod"]